# Configure Git to only push the current branch
git config --global push.default simple

ssh-add - <<< "${DEPLOY_SSH_KEY}"

# Remove .gitignore and replace with the production version
rm -f .gitignore
cp scripts/prodignore .gitignore
cat .gitignore

# Add the Linode production server as a remote repository
git remote add production ssh://koinos@173.255.232.131:/home/koinos/sphinxbare.git


# Add and commit all the static files generated by the Gatsby build
git add . && git commit -m "Sphinx build"

# Push all changes to the Linode production server
git push -f production HEAD:refs/heads/master