# add travis ssh key 
ssh-add - <<< "${DEPLOY_SSH_KEY}"

# Remove .gitignore and replace with the production version
rm -f .gitignore
cp scripts/prodignore .gitignore
cat .gitignore

# copy files inside the generated HTML directory to the webserver
rsync -azP ./docs/_build/html koinos@173.255.232.131:/var/www/html


# Add and commit all the static files generated by Sphinx
git add . && git commit -m "Sphinx build"

# Push all changes to the Linode production server
git push -f production HEAD:refs/heads/master